blank_issues_enabled: false
contact_links:
  - name: Issues related to a specific epic
    url: Issues-related-to-a-specific-epic.md
    about: Is it issue related to a specific epic?
  - name: Production Issue
    url: Production-issues.md
    about: If you have a Production issue?
  - name: Other issues
    url: Other-Issues.md
    about: Is it a bug to be reported?
