blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: Issues-related-to-a-specific-epic.md
    about: Please report security vulnerabilities here.
